import { Platform } from 'react-native';

export const CLASSIC_COLORS = [
  '#f2b157', '#ea7274', '#72a83d', '#5399cd', '#a9a9a9', '#b8943e', '#8e44ad', '#2c3e50'
];

export const THEMES = {
  DEFAULT: {
    id: 'DEFAULT',
    name: 'Minimal White',
    bg: '#F2F2F7',
    cardBg: '#FFFFFF',
    text: '#000000',
    accent: '#007AFF',
    secondary: '#E5E5EA',
    font: 'System',
    borderRadius: 24,
    borderWidth: 0,
    strokeLinecap: 'round',
    shadow: true,
  },
  DARK_MODE: {
    id: 'DARK_MODE',
    name: 'Midnight Black',
    bg: '#000000',
    cardBg: '#1C1C1E',
    text: '#FFFFFF',
    accent: '#FFD60A',
    secondary: '#2C2C2E',
    font: 'System',
    borderRadius: 24,
    borderWidth: 0,
    strokeLinecap: 'round',
    shadow: false,
  },
  MINECRAFT: {
    id: 'MINECRAFT',
    name: 'Minecraft',
    bg: '#18100C', // Toprak
    cardBg: '#3B2820', // Ahşap
    text: '#FFFFFF',
    accent: '#589028', // Çimen Yeşili
    secondary: '#291D17',
    font: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    borderRadius: 0, // Kare bloklar
    borderWidth: 4,
    borderColor: '#120B08',
    strokeLinecap: 'butt', // Küt uçlar
    shadow: false,
  },
  CYBERPUNK: {
    id: 'CYBERPUNK',
    name: 'Cyberpunk 2077',
    bg: '#050505',
    cardBg: '#111',
    text: '#FCEE0A',
    accent: '#00F0FF',
    secondary: '#333',
    font: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: '#FCEE0A',
    strokeLinecap: 'butt',
    shadow: false,
  },
  MATRIX: {
    id: 'MATRIX',
    name: 'Matrix / Hacker',
    bg: '#000000',
    cardBg: '#0D0D0D',
    text: '#00FF41',
    accent: '#003B00',
    secondary: '#1A1A1A',
    font: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    borderRadius: 0,
    borderWidth: 1,
    borderColor: '#00FF41',
    strokeLinecap: 'butt',
    shadow: false,
  },
  HOGWARTS: {
    id: 'HOGWARTS',
    name: 'Hogwarts',
    bg: '#221C16',
    cardBg: '#3E3224',
    text: '#E0C086',
    accent: '#740001', // Gryffindor
    secondary: '#2C241C',
    font: 'serif',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E0C086',
    strokeLinecap: 'round',
    shadow: true,
  },
  STARWARS: {
    id: 'STARWARS',
    name: 'Star Wars',
    bg: '#000000',
    cardBg: '#111111',
    text: '#FFE81F',
    accent: '#FF3333', // Sith Kırmızısı
    secondary: '#222',
    font: 'System',
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#FFE81F',
    strokeLinecap: 'round',
    shadow: false,
  },
  MARVEL: {
    id: 'MARVEL',
    name: 'Avengers',
    bg: '#18191A',
    cardBg: '#242526',
    text: '#FFFFFF',
    accent: '#ED1D24',
    secondary: '#3A3B3C',
    font: 'System',
    borderRadius: 12,
    borderWidth: 0,
    strokeLinecap: 'round',
    shadow: true,
  },
  RETRO: {
    id: 'RETRO',
    name: 'Neon 80s',
    bg: '#2b0f36',
    cardBg: '#401852',
    text: '#ff2a6d',
    accent: '#05d9e8',
    secondary: '#361345',
    font: 'System',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#ff2a6d',
    strokeLinecap: 'round',
    shadow: true,
  },
  LOL: {
    id: 'LOL',
    name: 'League of Legends',
    bg: '#091428',
    cardBg: '#0A323C',
    text: '#C8AA6E',
    accent: '#0AC8B9',
    secondary: '#092736',
    font: 'serif',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#C8AA6E',
    strokeLinecap: 'round',
    shadow: true,
  },
  VALORANT: {
    id: 'VALORANT',
    name: 'Valorant',
    bg: '#0F1923',
    cardBg: '#1F2326',
    text: '#FFFFFF',
    accent: '#FD4556',
    secondary: '#283138',
    font: 'System',
    borderRadius: 4,
    borderWidth: 0,
    strokeLinecap: 'butt',
    shadow: false,
  },
  GTA: {
    id: 'GTA',
    name: 'GTA V',
    bg: '#354633',
    cardBg: '#222',
    text: '#FFFFFF',
    accent: '#568f3f',
    secondary: '#000',
    font: 'System',
    borderRadius: 0,
    borderWidth: 0,
    strokeLinecap: 'butt',
    shadow: false,
  }
};